name: myAutomatisation

on:
  push:
    branches: [ "main" ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Hello step
      run : echo "Hello from GitHub Actions!"

    - name: Clone Repository
      uses: actions/checkout@v3
      
    - name: List Directories
      run: ls -la

  bye:
    runs-on: ubuntu-latest
    needs: [hello]
    
    steps:
      - name: Bye step
        run : echo "Bye bye!"

  run-script:
    runs-on: ubuntu-latest
    needs: [hello]

    steps: 
    - name: Install Python 3.14
      uses: action/step-python@v3
      with: 
        python-version: "3.14"

    - name: Run my script
      run: python3 MyNumbers.py
